### PR TITLE
replace deprecated package with typing_extensions

### LINKED ISSUE #338: ValueError: wrapper has not been initialized in jwcrypto Library
**Issue Title:**

`ValueError: wrapper has not been initialized` in `jwcrypto` Library (Python 3.12, jwcrypto 1.51, macOS)

**Description:**

I am encountering an issue with the `jwcrypto` library in my Python 3.12 project on macOS. The error message `ValueError: wrapper has not been initialized` is being raised during the initialization of a Python debugging tool.

**Environment:**

- **Python Version:** 3.12
- **Library Version:** 1.51
- **Operating System:** macOS (Specify your macOS version if applicable)

**Steps to Reproduce:**

1. Start the Python debugging tool on pycharm.
2. Observe the error `ValueError: wrapper has not been initialized` during tool initialization.

**stacktrace**
```
  File "/venv/lib/python3.12/site-packages/jwcrypto/jwk.py", line 301, in <module>
    class JWK(dict):
  File "/venv/lib/python3.12/site-packages/jwcrypto/jwk.py", line 769, in JWK
    @deprecated
     ^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/deprecated/classic.py", line 276, in deprecated
    @wrapt.decorator(adapter=adapter)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/wrapt/decorators.py", line 427, in decorator
    return _build(wrapper, _wrapper, adapter=decorator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/wrapt/decorators.py", line 239, in _build
    return AdapterWrapper(wrapped=wrapped, wrapper=wrapper,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle/pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle/pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
ValueError: wrapper has not been initialized
```

### PR DESCRIPTION
**Pull request by david-homelend**
fixes #338

### CODE REVIEW

**Review by simo5 — APPROVED** [review]
LGTM!
Thanks

**Comment by simo5** [comment]
Would you mind adding a sign-off-by line in your commit?

**Comment by david-homelend** [comment]
is this ok?

**Comment by simo5** [comment]
Perfect, thank you

**Comment by simo5** [comment]
I was not planning a release just yet, is this something that would warrant a 1.5.2 on its own ?

**Comment by christianplatta1012** [comment]
We have also IntelliJ IDEA debugger problems. A new release would be greatly appreciated :-)

**Comment by simo5** [comment]
https://github.com/latchset/jwcrypto/releases/tag/v1.5.2

**Comment by bobleckelibm** [comment]
Hi team — wondering if anyone checked in 3.6 whether this was working for them? I know that 3.6 is well beyond EOL but we still support it and our builds started breaking a few hours ago when jwcrypto 1.5.2 was released. Seems from intial tracking that its from the import change. I can reproduce in 3.6.15: 

```$ python
Python 3.6.15 (default, Oct 17 2023, 13:49:36)
[GCC Apple LLVM 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing_extensions import deprecated
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'deprecated'
```

Curious if this was considered or if we should simply pin to `<1.5.2`

**Comment by simo5** [comment]
I did consider it briefly, but 3.6 was deprecated for a while and removed from CI here: https://github.com/latchset/jwcrypto/commit/4f6cf303f6590fae98cb933d969ac4dd76c6cb2d

**Comment by bobleckelibm** [comment]
Fair enough @simo5 — would it then be possible to update https://github.com/latchset/jwcrypto/blob/main/setup.py#L43?

**Comment by bobleckelibm** [comment]
I guess that would only be worthwhile if 1.5.2 was yanked first... Not sure if you're willing to do that

**Comment by simo5** [comment]
Upstream python 3.6 support was over 2 years ago even for security: https://endoflife.date/python

**Comment by simo5** [comment]
> Fair enough @simo5 — would it then be possible to update https://github.com/latchset/jwcrypto/blob/main/setup.py#L43?

Would you mind opening an issue about this so I do not forget?

**Pull request merged**
