### PR TITLE
Turn JWK into a dict-like object

### LINKED ISSUE #27: Dictionary Interface for JWK
JWK should have a dict-like interface. You should be able to get, set and delete. Bonus points if JWK inherits from dict.

### PR DESCRIPTION
**Pull request by simo5**
This PR changes JWK to inherit from dict, and behave like a dictionary

Fixes #27

### CODE REVIEW

**Comment by simo5** [comment]
@npmccallum PTAL

**Comment by simo5** [comment]
@tiran PTAL at the second patch especially

**Comment by simo5** [comment]
Couldn't get reviews, closing for now, will reopen if there is demand

**Comment by npmccallum** [comment]
@simo5 I somehow missed the first ping. LGTM if you want to merge it.

**Comment by simo5** [comment]
@npmccallum respinning as it had a conflict, will push if it still passes CI

**Pull request merged**
