### PR TITLE
Better validation of JWE compact serialization

### LINKED ISSUE #92: Not passing a protected header when creating a compact JWE causes KeyError
Minimal test case:

```python
# testcase.py
from jwcrypto.jwe import JWE
from jwcrypto.jwk import JWK

payload = "some payload text"

jwe = JWE(payload)

key = JWK.generate(kty='RSA', size=4096)

header = {
    "alg": "RSA-OAEP-256",
    "enc": "A256CBC-HS512",
    "typ": "JWE",
}

jwe.add_recipient(key, header)

serialised = jwe.serialize(compact=True)
```

```
$ python testcase.py
Traceback (most recent call last):
  File "testcase.py", line 18, in <module>
    serialised = jwe.serialize(compact=True)
  File "/home/michael/code/jwcrypto/jwcrypto/jwe.py", line 285, in serialize
    ph = json_decode(self.objects['protected'])
KeyError: 'protected'
```

It seems like this is a fairly easy fix to initialise the 'protected' key in 'objects' to `{}`, but I'm not sure if this is allowed by the JWE spec?

### PR DESCRIPTION
**Pull request by simo5**
Fixes #92

### CODE REVIEW

**Comment by simo5** [comment]
@michaelboulton @tiran PTAL

**Comment by michaelboulton** [comment]
It looks good, the only thing I'd suggest is to tack on a few examples of public/private key encryption with a JWE in the docs (could just copy this from the original issue: https://github.com/latchset/jwcrypto/issues/92#issuecomment-343958847) because it seems like there is about 3(?) different ways of doing it at the moment.

**Comment by simo5** [comment]
@michaelboulton yes please if you want to add both test and docs in a new PR on top of this one, that is very welcome

**Comment by simo5** [comment]
@tiran ok to push ?

**Comment by michaelboulton** [comment]
This is the test I was using when checking, if it helps
```python
...
class TestJWE(unittest.TestCase):
...
    def test_protected_headers_required(self):
        """Compact representation requires a protected header

        https://github.com/latchset/jwcrypto/issues/92#issuecomment-343764886
        """

        payload = "some payload text"

        e = jwe.JWE(payload)

        key = jwk.JWK.generate(kty='RSA', size=4096)

        header = {
            "alg": "RSA-OAEP-256",
            "enc": "A256CBC-HS512",
            "typ": "JWE",
        }

        e.add_recipient(key, header)

        with self.assertRaises(jwe.InvalidJWEOperation):
            e.serialize(compact=True)
```

**Comment by simo5** [comment]
Thanks @michaelboulton, used it for inspiration

**Comment by simo5** [comment]
@tiran, tests added, PTAL

**Comment by tiran** [comment]
CI is failing

```
jwcrypto/tests.py:856:21: E128 continuation line under-indented for visual indent
                    aad='XYZ', recipient=E_A1_ex['key'])
                    ^
jwcrypto/tests.py:861:21: E128 continuation line under-indented for visual indent
                    unprotected='{"jku":"https://example.com/keys.jwks"}',
                    ^
jwcrypto/tests.py:862:21: E128 continuation line under-indented for visual indent
                    recipient=E_A1_ex['key'])
```

**Comment by simo5** [comment]
Fixed the indentantion, now passes.
@tiran, PTAL

**Pull request merged**
